# Generated by Django 2.2.1 on 2019-07-01 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 1, 17, 47, 10, 131160, tzinfo=utc))),
                ('medicines', models.BinaryField()),
                ('reports', models.BinaryField()),
                ('diagnosis', models.BinaryField()),
                ('other', models.BinaryField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
