# Generated by Django 2.2.1 on 2019-07-04 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20190701_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 7, 4, 8, 41, 37, 613099, tzinfo=utc)),
        ),
    ]
