# Generated by Django 2.2.1 on 2019-06-21 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20190621_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 21, 7, 16, 34, 735519, tzinfo=utc)),
        ),
    ]
