# Generated by Django 2.2.1 on 2019-06-21 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_auto_20190621_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 21, 10, 4, 47, 965278, tzinfo=utc)),
        ),
    ]
