# Generated by Django 2.2.1 on 2019-07-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('password', models.CharField(default='6e8429a51fb089890b60fbb54d209fb74af8dca3c91cee0bfa5ab453d883cd99', max_length=100)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('add', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
