# Generated by Django 2.2.1 on 2019-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointments',
            field=models.BinaryField(null=True),
        ),
    ]
