# Generated by Django 2.2.1 on 2019-06-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='c04c4a49c663a208f25b785502678574dc862a0f6addac01c2b88ee953cc2907', max_length=100),
        ),
    ]
