# Generated by Django 2.2.1 on 2019-05-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('reg_no', models.CharField(max_length=20)),
                ('spl', models.CharField(max_length=20)),
                ('work_add', models.CharField(max_length=100)),
            ],
        ),
    ]
