# Generated by Django 2.2.1 on 2019-07-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_detail', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('reg_no', models.CharField(max_length=20)),
                ('spl', models.CharField(max_length=20)),
                ('work_add', models.CharField(max_length=100)),
                ('password', models.CharField(default='6e8429a51fb089890b60fbb54d209fb74af8dca3c91cee0bfa5ab453d883cd99', max_length=100)),
                ('phone', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
