# Generated by Django 2.2.1 on 2019-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='doctor',
            name='appointments',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slots',
            field=models.BinaryField(null=True),
        ),
    ]
