# Generated by Django 2.2.1 on 2019-05-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('doe', models.DateField()),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='pharmacy',
        ),
    ]
